/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard-scss', 'stylelint-config-recess-order', 'stylelint-config-css-modules'],
  plugins: ['stylelint-scss'],
  ignoreFiles: ['dist/*', 'node_modules/*'],
  rules: {
    'alpha-value-notation': 'number',
    'at-rule-empty-line-before': 'never',
    'color-function-notation': 'legacy',
    'color-function-alias-notation': 'with-alpha',
    'comment-empty-line-before': 'never',
    'custom-property-empty-line-before': 'never',
    'declaration-block-no-redundant-longhand-properties': null,
    'declaration-empty-line-before': 'never',
    'font-family-no-missing-generic-family-keyword': null,
    'function-name-case': null,
    'function-url-quotes': ['always', { except: ['empty'] }],
    'media-feature-range-notation': 'prefix',
    'no-descending-specificity': null,
    'no-duplicate-selectors': null,
    'no-irregular-whitespace': null,
    'number-max-precision': 10,
    'order/properties-order': null,
    'property-no-vendor-prefix': null,
    'rule-empty-line-before': 'never',
    'scss/operator-no-unspaced': null,
    'selector-attribute-quotes': 'never',
    'selector-not-notation': 'simple',
    'shorthand-property-no-redundant-values': null,
    'value-keyword-case': null,
  },
};
